### ISSUE TITLE
Regression in 0.7.0

### ISSUE THREAD

**Issue by dblock** [joshbuddy/jsonpath#79]
```ruby
require 'json'
require 'jsonpath'

json = {
  ok: true,
  channels: [
    {
      id: 'C09C5GYHF',
      name: 'general'
    },
    {
      id: 'C09C598QL',
      name: 'random'
    }
  ]
}.to_json

p JsonPath.on(json, "$..[?(@.name=='general')].id")
```

With 0.5.8

```
["C09C5GYHF"]
```

With 0.7.0 or newer

```
["C09C5GYHF", "C09C5GYHF", "general"]
```

I am possibly misunderstanding the syntax?

**Comment by Skarlso** [comment]
Hey @dblock.

Going to look at this is a moment.

**Comment by Skarlso** [comment]
Interesting. It does seem to not work for some reason. :/ Going to investigate and fix.

**Comment by dblock** [comment]
A different but similar regression that doesn't work with a workaround.

```ruby
json = {
  ok: true,
  channels: [
    {
      id: 'C09C5GYHF',
      name: 'general',
      is_archived: false
    },
    {
      id: 'C09C598QL',
      name: 'random',
      is_archived: true
    }
  ]
}.to_json

p JsonPath.on(json, "$..channels[?(@.is_archived==false)].id")
```

**Comment by Skarlso** [comment]
Fixed the second regression of boolean values.

**Comment by Skarlso** [comment]
Merged the boolean thing. Working on the first one. It's interesting. I think it's the parsers fault at a first glance. :/ Going to try and take it apart step by step.

**Comment by dblock** [comment]
I’m glad I created some interesting work for you :)

More seriously it’s very much appreciated!

**Comment by Skarlso** [comment]
Ey, no worries, Thanks! There was some risk involved when I switched to the parser from eval. But I think it was worth it, considering the security risk of eval. :) There were bound to be problems. Honestly, I'm glad you found some, I was beginning to think that the bugs might be more obscure. :)

**Comment by Skarlso** [comment]
@dblock So turns out I made a grave mistake during refactoring. And some of the tests I've wrote weren't supposed to work the way I wrote them. But this gem was working incorrectly and thus the tests were passing.

I confirmed with the jsonpath online evaluator. :/

Massive thanks for this issue. I don't think I would have ever found out otherwise.

**Comment by Skarlso** [comment]
@dblock Success!!!!!! \o/ So turns out, my dig implementation was flawed as well. I was mimicking the ruby implementation which said, if hash is not a hash it should return the hash. However, I forgot that ruby also had this dig in the hash class, while mine was being able to be called by anyone leading to get `general` returned as `general` for which the evaluation was `general == general`. Which was true and that's why it was yielded and it ended up as `['C09C5GYHF', 'general']`.

Man this was a bitch to track down if I might say so. Also, also it turns out that I'm supporting a bit of more magic with expressions as the original jsonpath specification. For example this is possible:
`$..mentions.type[?(@ == '@Place')]` which isn't in jsonpath. And this was possible because dig returned the hash which was a string. So this was the second flaw once I fixed dig I had to uncover.

Luckily this came more easy because I found out that elements was empty if only `@` was provided as an expression. Which lead to a simple If. 

Maaaaaaaan!! THANK YOU for this. It was fun and frustrating and I'm super happy that these issues are now out of JsonPath. Thank you!

**Comment by joshbuddy** [comment]
👏 👏 👏 

well done!

**Comment by dblock** [comment]
🆒

**Comment by Skarlso** [comment]
Now, if there aren't any further issues, I'm closing this one. :) Please re-open if anything surfaces.
